### PR TITLE
Abstract pattern class

### PR DESCRIPTION
**Pull request by kmaric69**
I've added an abstract class for registering Block Patterns.

I will add one more for Block pattern categories and for modifying the default WordPress patterns + categories.

### CODE REVIEW

**Review by iruzevic — CHANGES_REQUESTED** [review]
Looks good but you are missing:

- [ ] WP-CLI command for example
- [ ] Tests

**Review by IvanGrginovInf — APPROVED** [review]

**Comment by IvanGrginovInf** [comment]
@iruzevic, @dingo-d do you have an idea why this PR has failing tests with the following error? (as you can see from files changed, I didn't touch those files or anything related to them)

```
 Tests\Blocks\BlocksCliTest > Blocks CLI command will correctly copy the Blocks class with defaults
   Mockery\Exception\BadMethodCallException 

  Static method WP_CLI::runcommand() does not exist on this mock object

  at src/Blocks/BlocksCli.php:133
    129▕ 		system("cp -R {$rootNode}/src/Blocks/assets/. {$folders['assets']}/");
    130▕ 		system("cp -R {$rootNode}/src/Blocks/variations/. {$folders['variations']}/");
    131▕ 		system("cp -R {$rootNode}/src/Blocks/manifest.json {$folders['blocks']}/");
    132▕ 
  ➜ 133▕ 		\WP_CLI::runcommand("{$this->commandParentName} use_wrapper {$this->prepareArgsManual($args)}");
    134▕ 
    135▕ 		foreach (static::COMPONENTS as $component) {
    136▕ 			\WP_CLI::runcommand("{$this->commandParentName} use_component --name='{$component}' {$this->prepareArgsManual($args)}");
    137▕ 		}

  1   src/Blocks/BlocksCli.php:93
      EightshiftLibs\Blocks\BlocksCli::blocksInit()

  2   tests/Blocks/BlocksCliTest.php:38
      EightshiftLibs\Blocks\BlocksCli::__invoke()

  • Tests\Blocks\BlocksCliTest > Blocks CLI command will correctly copy the Blocks class with set arguments
   Mockery\Exception\BadMethodCallException 

  Static method WP_CLI::runcommand() does not exist on this mock object

  at src/Blocks/BlocksCli.php:133
    129▕ 		system("cp -R {$rootNode}/src/Blocks/assets/. {$folders['assets']}/");
    130▕ 		system("cp -R {$rootNode}/src/Blocks/variations/. {$folders['variations']}/");
    131▕ 		system("cp -R {$rootNode}/src/Blocks/manifest.json {$folders['blocks']}/");
    132▕ 
  ➜ 133▕ 		\WP_CLI::runcommand("{$this->commandParentName} use_wrapper {$this->prepareArgsManual($args)}");
    134▕ 
    135▕ 		foreach (static::COMPONENTS as $component) {
    136▕ 			\WP_CLI::runcommand("{$this->commandParentName} use_component --name='{$component}' {$this->prepareArgsManual($args)}");
    137▕ 		}
```

**Comment by iruzevic** [comment]
> I've taken over this feature because we need patterns for a project.
> 
> Added tests & wp cli command.
> 
> @iruzevic, @dingo-d do you have an idea why this PR has failing tests with the following error? (as you can see from files changed, I didn't touch those files or anything related to them)
> 
> ```
>  Tests\Blocks\BlocksCliTest > Blocks CLI command will correctly copy the Blocks class with defaults
>    Mockery\Exception\BadMethodCallException 
> 
>   Static method WP_CLI::runcommand() does not exist on this mock object
> 
>   at src/Blocks/BlocksCli.php:133
>     129▕ 		system("cp -R {$rootNode}/src/Blocks/assets/. {$folders['assets']}/");
>     130▕ 		system("cp -R {$rootNode}/src/Blocks/variations/. {$folders['variations']}/");
>     131▕ 		system("cp -R {$rootNode}/src/Blocks/manifest.json {$folders['blocks']}/");
>     132▕ 
>   ➜ 133▕ 		\WP_CLI::runcommand("{$this->commandParentName} use_wrapper {$this->prepareArgsManual($args)}");
>     134▕ 
>     135▕ 		foreach (static::COMPONENTS as $component) {
>     136▕ 			\WP_CLI::runcommand("{$this->commandParentName} use_component --name='{$component}' {$this->prepareArgsManual($args)}");
>     137▕ 		}
> 
>   1   src/Blocks/BlocksCli.php:93
>       EightshiftLibs\Blocks\BlocksCli::blocksInit()
> 
>   2   tests/Blocks/BlocksCliTest.php:38
>       EightshiftLibs\Blocks\BlocksCli::__invoke()
> 
>   • Tests\Blocks\BlocksCliTest > Blocks CLI command will correctly copy the Blocks class with set arguments
>    Mockery\Exception\BadMethodCallException 
> 
>   Static method WP_CLI::runcommand() does not exist on this mock object
> 
>   at src/Blocks/BlocksCli.php:133
>     129▕ 		system("cp -R {$rootNode}/src/Blocks/assets/. {$folders['assets']}/");
>     130▕ 		system("cp -R {$rootNode}/src/Blocks/variations/. {$folders['variations']}/");
>     131▕ 		system("cp -R {$rootNode}/src/Blocks/manifest.json {$folders['blocks']}/");
>     132▕ 
>   ➜ 133▕ 		\WP_CLI::runcommand("{$this->commandParentName} use_wrapper {$this->prepareArgsManual($args)}");
>     134▕ 
>     135▕ 		foreach (static::COMPONENTS as $component) {
>     136▕ 			\WP_CLI::runcommand("{$this->commandParentName} use_component --name='{$component}' {$this->prepareArgsManual($args)}");
>     137▕ 		}
> ```

not sure, this features is old maybe try pulling the latest branch to this one

**Comment by IvanGrginovInf** [comment]
> not sure, this features is old maybe try pulling the latest branch to this one
@iruzevic it's up to date with `release/3.1.0`. Also tried creating a new branch from `release/3.1.0` and copy / pasting the files there, same issue.

**Comment by dingo-d** [comment]
It looks like the runcommand isn't mocked.

**Review by iruzevic — APPROVED** [review]

**Pull request merged**
