### PR TITLE
Fix/phpstan max

### PR DESCRIPTION
**Pull request by szepeviktor**
@dingo-d Please help me mitigate undefined `Manifest_Data::get_config()` - the last obsticle

### CODE REVIEW

**Comment by dingo-d** [comment]
Adding

```php
  /**
   * Config getter
   *
   * @since 2.2.0 Added config getter.
   *
   * @return Config_Data
   */
  public function get_config();
```

To `interface-manifest-data.php` (with appropriate `use` statement `use Eightshift_Libs\Core\Config_Data;`), and removing `object` from the return value of the `get_config()` method in the `class-manifest.php` seems to fix the `Call to an undefined method Eightshift_Libs\Manifest\Manifest_Data::get_config` issue.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by szepeviktor** [comment]
Thank you for providing me a task to work on.

**Comment by dingo-d** [comment]
Thank you for helping us out 🙂  We really appreciate it.

**Pull request merged**
