### PR TITLE
Fix plugin install for GitHub plugins

### PR DESCRIPTION
**Pull request by IvanGrginovInf**
Because of the way `wp plugin install` works with remote zips (it appends a random hash at the end of the file after unzipping) and you can't change the name of the archive, we need to do it like this:

1. Download `release.zip` from a repo and save it as the correct plugin name (for example: `eightshift-forms.zip`)
2. Install from the local file and delete afterwards

### CODE REVIEW

**Review by iruzevic — APPROVED** [review]

**Comment by dingo-d** [comment]
Not sure I understand this. The `wp plugin install https://github.com/{$name}/releases/download/{$version}/release.zip` command won't install a plugin or?

**Comment by IvanGrginovInf** [comment]
> Not sure I understand this. The `wp plugin install https://github.com/{$name}/releases/download/{$version}/release.zip` command won't install a plugin or?

It will install it as `release-asdabdd`. And then the next time you run the update, it will add another plugin with a different name (meaning you will have a duplicate plugin in the list of installed plugins in WP admin) rather than updating the existing one. Also the folder name will be incorrect.

**Comment by dingo-d** [comment]
Wow, didn't know about that. That's odd.

**Review by dingo-d — APPROVED** [review]

**Comment by IvanGrginovInf** [comment]
> Wow, didn't know about that. That's odd.

@dingo-d  Yeah, not sure what's happening there. You can try running this in any project 2-3 times and you'll see what I mean.

`wp plugin install https://github.com/infinum/eightshift-forms/releases/download/0.2.2/release.zip`

**Pull request merged**
