### PR TITLE
adding PR template

### PR DESCRIPTION
**Pull request by iruzevic**
Added:
- Question template -  https://github.com/infinum/eightshift-libs/blob/feature/PR-template/.github/ISSUE_TEMPLATE/question.yml
- feature request - https://github.com/infinum/eightshift-libs/blob/feature/PR-template/.github/ISSUE_TEMPLATE/feature_request.yml
- bug report - https://github.com/infinum/eightshift-libs/blob/feature/PR-template/.github/ISSUE_TEMPLATE/bug_report.yml
- PR review template

### CODE REVIEW

**Comment by dingo-d** [comment]
I was planing on unifying the issue and pr templates for all of Infinum's os projects similar to this repo: https://github.com/WordPress/gutenberg/tree/trunk/.github

Their templates for issues and PRs are really good. Can you see what you can use from that repo (I like the way they added the comment part with the preview inside)? 

Don't copy paste ofc, but see what can we do in a similar fashion 🙂

**Comment by iruzevic** [comment]
> I was planing on unifying the issue and pr templates for all of Infinum's os projects similar to this repo: https://github.com/WordPress/gutenberg/tree/trunk/.github
> 
> Their templates for issues and PRs are really good. Can you see what you can use from that repo (I like the way they added the comment part with the preview inside)?
> 
> Don't copy paste ofc, but see what can we do in a similar fashion 🙂

uuu nice this looks soo nice

**Comment by iruzevic** [comment]
> I was planing on unifying the issue and pr templates for all of Infinum's os projects similar to this repo: https://github.com/WordPress/gutenberg/tree/trunk/.github
> 
> Their templates for issues and PRs are really good. Can you see what you can use from that repo (I like the way they added the comment part with the preview inside)?
> 
> Don't copy paste ofc, but see what can we do in a similar fashion 🙂

I have updated everything and it looks awesome :D

**Review by gabriel-glo — APPROVED** [review]
Nice

**Review by simun-ivanac — APPROVED** [review]

**Review by volfkarlo — APPROVED** [review]
Seems good! 😄

**Review by dadadavorin — APPROVED** [review]
👍

**Pull request merged**
